---

  - name: reload systemd
    systemd:
      daemon_reload: True
    changed_when: False

  - name: reload kboxes
    shell: "docker-compose up -d"
    args:
      chdir: "{{ item.value.path }}"
    with_dict: "{{ k_boxes }}"
    changed_when: False