---

  - name: reload systemd
    systemd:
      daemon_reload: True
    changed_when: False
    when: not lookup('env', 'MOLECULE_FILE') # skip when running tests

  - name: reload kboxes
    shell: "docker-compose up -d" # noqa 305
    args:
      chdir: "{{ item.value.path }}"
    with_dict: "{{ k_boxes }}"
    changed_when: False
    when: not lookup('env', 'MOLECULE_FILE') # skip when running tests