---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:10 # buster
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
