name: CI

on: 
  push:
    branches: 
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Tests Ansible Role
    runs-on: ubuntu-latest
    container: 
      image: quay.io/ansible/molecule:3.1.5
      options: --user root 
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
    - name: Run Testsuite
      run: |
        molecule test
