name: CI

on: 
  push:
    branches: 
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Tests Ansible Role
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
    - name: Run Testsuite
      run: |
        pwd
        ls -la
        docker run --rm -t \
          -v "$(pwd)":/molecule/kbox/ \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -w /molecule/kbox/ \
          quay.io/ansible/molecule:3.1.5 \
          molecule test
